#!/bin/sh

FILE="./a5_b1_topdeletions.csv"
TOP=20

csv2tsv() {
	sed -E 's/("([^"]*)")?,/\2\t/g' $1 > $2
}

general_subs() {
# General substitutions
	cat "$1" | sed 1d | sed "$TOP"q |
	sed -e 's/\t/\t\&\t/g' \
	-e 's/_/\\_/g'  \
	-e 's:-->:\$\\rightarrow\$:g' \
	-e 's:<=>:\$\\leftrightarrow\$:g' \
	-e 's:$:\t\\\\:g' > "$2"
}

add_latex(){
# Latex table syntax
ed -s $1 << END
1i
\resizebox{\textwidth}{!}{%
\rowcolors{2}{gray!25}{white}
\begin{tabular}{llll}
\toprule
ID	&	Name	&	Formula	&	Counts (\\%) \\\\
\midrule
.
\$a
\end{tabular}}
.
wq
END
}


csv2tsv "$FILE" "temp.tsv"
general_subs "temp.tsv" "table.tex"
add_latex "table.tex"
rm temp.tsv
