#!/bin/sh

set -e
if [ "$#" != "1" ]; then
	echo "error. usage: $0 pf_path" && exit
else
	pf_path=$1
fi
#outname=$(mc_shiftindex $pf_path | cut -d: -f2 | sed 's/ //')
fbname=$(basename "$pf_path" .csv)
mc_setcover "$pf_path"  --max 5000 | tee "${fbname}.covers"

