#!/bin/sh

cd ./results
mc_dir_pltcomp ./ -w 3 -x 3 -f Arial  -fs 12 -f2n ./f2n.tsv --x_order '[3,0,1,2]'
#mc_dir_pltcomp ./ -w 3 -x 3 -f Arial  -fs 12 --normalize  -f2n ./f2n.tsv --x_order '[3,0,1,2]'
